#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l vmem=28gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=11

set -e
set -x

mkdir -p output
cp $(jq -r .bvecs config.json) output/dwi.bvecs
cp $(jq -r .bvals config.json) output/dwi.bvals
chmod -R +w output

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_denoise_mppca \
    --force \
    --out_dir output \
    --patch_radius $(jq -r .patch_radius config.json) \
    --pca_method $(jq -r .pca_method config.json) \
    --out_denoised dwi.nii.gz \
    $(jq -r .dwi config.json)

echo "done"
